services:
    imt.behat_profiling_extension.output:
        class: Symfony\Component\Console\Output\ConsoleOutput

    imt.behat_profiling_extension.listener.stopwatch:
        class: IMT\BehatProfilingExtension\Listener\StopwatchListener
        arguments:
            - "@imt.behat_profiling_extension.stopwatch"
            - "@imt.behat_profiling_extension.output"
        tags:
            - { name: event_dispatcher.subscriber }

    imt.behat_profiling_extension.stopwatch:
        class: Symfony\Component\Stopwatch\Stopwatch
